CREATE TABLE EP_AKUN_KODE_JASA
(
  KODE_JASA            VARCHAR2(50 BYTE),
  KODE_KEL_JASA        VARCHAR2(50 BYTE),
  AKUN_PEMBELIAN       VARCHAR2(10 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE),
  AKTIF                VARCHAR2(1 BYTE),
  KODE_KELOMPOK_INDUK  VARCHAR2(1 BYTE)
);


CREATE TABLE EP_KOM_BARANG
(
  KODE_BARANG      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG  VARCHAR2(50 BYTE),
  NAMA_BARANG      VARCHAR2(250 BYTE),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE),
  AKTIF            VARCHAR2(1 BYTE),
  CONSTRAINT EP_KOM_BARANG_PK
  PRIMARY KEY
  (KODE_BARANG, KODE_SUB_BARANG)
  ENABLE VALIDATE
);


CREATE TABLE EP_KOM_HARGA_BARANG
(
  KODE_HARGA_BARANG  INTEGER,
  KODE_BARANG        VARCHAR2(3 BYTE),
  KODE_SUB_BARANG    VARCHAR2(2 BYTE),
  KODE_KANTOR        VARCHAR2(5 BYTE),
  KODE_SUMBER        INTEGER,
  TGL_SUMBER         DATE,
  MATA_UANG          VARCHAR2(3 BYTE),
  HARGA              NUMBER(19,4),
  BIAYA_PENANGANAN   NUMBER(19,4),
  BIAYA_ASURANSI     NUMBER(19,4),
  BIAYA_KARGO        NUMBER(19,4),
  BEA_PAJAK          NUMBER(19,4),
  TOTAL_BIAYA        NUMBER(19,4),
  DISKON             NUMBER(19,4),
  KODE_VENDOR        INTEGER,
  AKTIF              VARCHAR2(1 BYTE),
  LAMPIRAN           VARCHAR2(255 BYTE),
  KETERANGAN         VARCHAR2(4000 BYTE),
  CATATAN            VARCHAR2(4000 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KOM_HARGA_JASA
(
  KODE_HARGA_JASA  INTEGER,
  KODE_JASA        VARCHAR2(50 BYTE),
  KODE_KEL_JASA    VARCHAR2(50 BYTE),
  KODE_KANTOR      VARCHAR2(5 BYTE),
  KODE_SUMBER      INTEGER,
  TGL_SUMBER       DATE,
  MATA_UANG        VARCHAR2(3 BYTE),
  HARGA            NUMBER(19,4),
  KODE_VENDOR      INTEGER,
  AKTIF            VARCHAR2(1 BYTE),
  STATUS           VARCHAR2(1 BYTE),
  LAMPIRAN         VARCHAR2(255 BYTE),
  KETERANGAN       VARCHAR2(4000 BYTE),
  CATATAN          VARCHAR2(4000 BYTE),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KOM_JASA
(
  KODE_JASA      VARCHAR2(50 BYTE),
  KODE_KEL_JASA  VARCHAR2(50 BYTE),
  NAMA_JASA      VARCHAR2(255 BYTE),
  STATUS         VARCHAR2(1 BYTE),
  KETERANGAN     VARCHAR2(4000 BYTE),
  CATATAN        VARCHAR2(4000 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_KOM_JASA_PK
  PRIMARY KEY
  (KODE_JASA)
  ENABLE VALIDATE
);


CREATE TABLE EP_KOM_KELOMPOK_JASA
(
  KODE_KEL_JASA  VARCHAR2(50 BYTE),
  NAMA_KEL_JASA  VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KOM_KOMENTAR
(
  KODE_KOMENTAR         INTEGER,
  KODE_HARGA            INTEGER,
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  TIPE                  VARCHAR2(50 BYTE),
  KOMENTAR              VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KOM_SUMBER_HARGA
(
  KODE_SUMBER    INTEGER,
  NAMA_SUMBER    VARCHAR2(50 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_DOK_INVOICE
(
  KODE_DOKUMEN   INTEGER,
  KODE_INVOICE   VARCHAR2(50 BYTE),
  KODE_KONTRAK   VARCHAR2(50 BYTE),
  KODE_KANTOR    VARCHAR2(5 BYTE),
  KODE_VENDOR    INTEGER,
  KATEGORI       VARCHAR2(64 BYTE),
  KETERANGAN     VARCHAR2(1024 BYTE),
  NAMA_FILE      VARCHAR2(255 BYTE),
  STATUS         CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_DOK_KONTRAK
(
  KODE_DOKUMEN    INTEGER,
  KODE_KONTRAK    VARCHAR2(50 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  KODE_KATEGORI   VARCHAR2(64 BYTE),
  KETERANGAN      VARCHAR2(1024 BYTE),
  NAMA_FILE       VARCHAR2(255 BYTE),
  STATUS          CHAR(1 BYTE),
  STATUS_PUBLISH  CHAR(1 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_INVOICE
(
  KODE_INVOICE        VARCHAR2(50 BYTE),
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_VENDOR         INTEGER,
  TGL_INVOICE         DATE,
  NAMA_VENDOR         VARCHAR2(250 BYTE),
  AKUN_BANK           VARCHAR2(200 BYTE),
  TGL_BUAT            DATE,
  STATUS              VARCHAR2(2 BYTE),
  POSISI_PERSETUJUAN  INTEGER,
  TGL_DISETUJUI       DATE,
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_ITEM_INVOICE
(
  KODE_ITEM         INTEGER,
  KODE_INVOICE      VARCHAR2(50 BYTE),
  KODE_KONTRAK      VARCHAR2(50 BYTE),
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KODE_VENDOR       INTEGER,
  NO_BASTP          VARCHAR2(50 BYTE),
  NILAI_BASTP       NUMBER(18),
  MATA_UANG_BASTP   VARCHAR2(50 BYTE),
  PENALTI_BASTP     NUMBER(18),
  PPH23_BASTP       NUMBER(18),
  PPN_BASTP         NUMBER(18),
  DP_BASTP          NUMBER(18),
  SUBTOTAL_BASTP    NUMBER(18),
  KETERANGAN_BASTP  VARCHAR2(4000 BYTE),
  KOMENTAR_BASTP    VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_ITEM_KONTRAK
(
  KODE_KONTRAK          VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(1024 BYTE),
  HARGA                 NUMBER(19,4),
  JUMLAH                NUMBER(18),
  MIN_QTY               NUMBER(18),
  MAX_QTY               NUMBER(18),
  SATUAN                VARCHAR2(50 BYTE),
  SUB_TOTAL             NUMBER(19,4),
  KETERANGAN_LENGKAP    VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_ITEM_PERKEMBANGAN
(
  KODE_ITEM_PERKEMBANGAN  INTEGER,
  KODE_PERKEMBANGAN       INTEGER,
  KODE_PO                 VARCHAR2(50 BYTE),
  KODE_KONTRAK            VARCHAR2(50 BYTE),
  KODE_KANTOR             VARCHAR2(5 BYTE),
  KODE_PO_ITEM            INTEGER,
  QTY_PERKEMBANGAN        INTEGER,
  QTY_DISETUJUI           INTEGER,
  TGL_REKAM               DATE,
  PETUGAS_REKAM           VARCHAR2(10 BYTE),
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_ITEM_PERUBAHAN
(
  KODE_PERUBAHAN        INTEGER,
  KODE_KONTRAK          VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(255 BYTE),
  HARGA                 NUMBER(19,4),
  JUMLAH                NUMBER(18),
  MIN_QTY               NUMBER(18),
  MAX_QTY               NUMBER(18),
  SATUAN                VARCHAR2(10 BYTE),
  SUB_TOTAL             NUMBER(19,4),
  KETERANGAN_LENGKAP    VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JAMINAN_PEL_KONTRAK
(
  KODE_JAMINAN    INTEGER,
  KODE_KONTRAK    VARCHAR2(50 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  NOMOR           VARCHAR2(50 BYTE),
  DIBUAT_OLEH     VARCHAR2(255 BYTE),
  TGL_BUAT        DATE,
  TGL_KADALUARSA  DATE,
  MATA_UANG       VARCHAR2(3 BYTE),
  NILAI           NUMBER(19,4),
  LAMPIRAN        VARCHAR2(255 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JAMINAN_PEL_PERUBAHAN
(
  KODE_PERUBAHAN  INTEGER,
  KODE_JAMINAN    INTEGER,
  KODE_KONTRAK    VARCHAR2(50 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  NOMOR           VARCHAR2(50 BYTE),
  DIBUAT_OLEH     VARCHAR2(255 BYTE),
  TGL_BUAT        DATE,
  TGL_KADALUARSA  DATE,
  MATA_UANG       VARCHAR2(3 BYTE),
  NILAI           NUMBER(19,4),
  LAMPIRAN        VARCHAR2(255 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JANGKA_KOMENTAR
(
  KODE_KOMENTAR       INTEGER,
  KODE_JANGKA         INTEGER,
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(150 BYTE),
  NAMA_KOMENTAR       VARCHAR2(50 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JANGKA_KONTRAK
(
  KODE_JANGKA              INTEGER,
  KODE_KONTRAK             VARCHAR2(50 BYTE),
  KODE_KANTOR              VARCHAR2(5 BYTE),
  PERSENTASI               INTEGER,
  TGL_TARGET               DATE,
  PERSENTASI_PERKEMBANGAN  INTEGER,
  STATUS_PERKEMBANGAN      VARCHAR2(2 BYTE),
  NO_BASTP                 VARCHAR2(50 BYTE),
  TGL_BASTP                DATE,
  JUDUL_BASTP              VARCHAR2(1024 BYTE),
  LAMPIRAN_BASTP           VARCHAR2(250 BYTE),
  TGL_BUAT_BASTP           DATE,
  STATUS_BASTP             CHAR(1 BYTE),
  POSISI_PERSETUJUAN       INTEGER,
  DP_PERSENTASI            INTEGER,
  KETERANGAN               VARCHAR2(4000 BYTE),
  KETERANGAN_BASTP         VARCHAR2(4000 BYTE),
  TGL_REKAM                DATE,
  PETUGAS_REKAM            VARCHAR2(10 BYTE),
  TGL_UBAH                 DATE,
  PETUGAS_UBAH             VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JANGKA_PERKEMBANGAN
(
  KODE_PERKEMBANGAN  INTEGER,
  KODE_JANGKA        INTEGER,
  KODE_KONTRAK       VARCHAR2(50 BYTE),
  KODE_KANTOR        VARCHAR2(5 BYTE),
  TGL_PERKEMBANGAN   DATE,
  PERSENTASI         INTEGER,
  STATUS             VARCHAR2(2 BYTE),
  KETERANGAN         VARCHAR2(4000 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_JANGKA_PERUBAHAN
(
  KODE_PERUBAHAN  INTEGER,
  KODE_JANGKA     INTEGER,
  KODE_KONTRAK    VARCHAR2(50 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  PERSENTASI      INTEGER,
  TGL_TARGET      DATE,
  KETERANGAN      VARCHAR2(4000 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_KOMENTAR_INVOICE
(
  KODE_KOMENTAR       INTEGER,
  KODE_INVOICE        VARCHAR2(50 BYTE),
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_VENDOR         INTEGER,
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(150 BYTE),
  NAMA_KOMENTAR       VARCHAR2(150 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_KOMENTAR_KONTRAK
(
  KODE_KOMENTAR       INTEGER,
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(150 BYTE),
  NAMA_KOMENTAR       VARCHAR2(50 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_KOMENTAR_PERUBAHAN
(
  KODE_KOMENTAR       INTEGER,
  KODE_PERUBAHAN      INTEGER,
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(250 BYTE),
  NAMA_KOMENTAR       VARCHAR2(50 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_KONTRAK
(
  KODE_KONTRAK         VARCHAR2(50 BYTE),
  KODE_KANTOR          VARCHAR2(5 BYTE),
  KODE_TENDER          VARCHAR2(50 BYTE),
  USER_PEMINTA         VARCHAR2(250 BYTE),
  JABATAN_PEMINTA      VARCHAR2(50 BYTE),
  KODE_VENDOR          INTEGER,
  NAMA_VENDOR          VARCHAR2(255 BYTE),
  TGL_TTD              DATE,
  TGL_MULAI            DATE,
  TGL_AKHIR            DATE,
  TGL_BUAT             DATE,
  JUDUL_PEKERJAAN      VARCHAR2(1024 BYTE),
  TIPE_KONTRAK         VARCHAR2(50 BYTE),
  JENIS_KONTRAK        VARCHAR2(50 BYTE),
  PESANAN_ULANG        CHAR(1 BYTE),
  MATA_UANG            VARCHAR2(3 BYTE),
  NILAI_KONTRAK        NUMBER(19,4),
  PERIODE_BAYAR_SEWA   INTEGER,
  UNIT_BAYAR_SEWA      VARCHAR2(50 BYTE),
  TERMIN_BAYAR_SEWA    VARCHAR2(100 BYTE),
  STATUS               VARCHAR2(2 BYTE),
  TGL_PEMUTUSAN        DATE,
  POSISI_PERSETUJUAN   VARCHAR2(50 BYTE),
  JUMLAH_PERUBAHAN     INTEGER,
  TGL_AKHIR_PENAWARAN  DATE,
  NILAI_JAMINAN        NUMBER(18),
  BANK_JAMINAN         VARCHAR2(250 BYTE),
  NO_JAMINAN           VARCHAR2(50 BYTE),
  TGL_MULAI_JAMINAN    DATE,
  TGL_AKHIR_JAMINAN    DATE,
  LAMPIRAN_JAMINAN     VARCHAR2(250 BYTE),
  UM_PERSENTASI        NUMBER(18,2),
  UM_NILAI             NUMBER(18),
  JABATAN_PEMBUAT      VARCHAR2(150 BYTE),
  ALASAN_PEMUTUSAN     VARCHAR2(4000 BYTE),
  CATATAN_PEMUTUSAN    VARCHAR2(4000 BYTE),
  LINGKUP_KERJA        VARCHAR2(4000 BYTE),
  CATATAN              VARCHAR2(4000 BYTE),
  DP_CATATAN           VARCHAR2(4000 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PEMERIKSAAN_KONTRAK
(
  KODE_KONTRAK   VARCHAR2(50 BYTE),
  KODE_KANTOR    VARCHAR2(5 BYTE),
  KODE_PARAM     VARCHAR2(50 BYTE),
  NAMA_PARAM     VARCHAR2(1024 BYTE),
  HASIL          INTEGER,
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PENUTUPAN_KONTRAK
(
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KEPUTUSAN_MASALAH   VARCHAR2(50 BYTE),
  KEPUTUSAN_WAN       VARCHAR2(50 BYTE),
  ALASAN_PENUTUPAN    VARCHAR2(4000 BYTE),
  PERNYATAAN_MASALAH  VARCHAR2(4000 BYTE),
  PERNYATAAN_WAN      VARCHAR2(4000 BYTE),
  EVAL_TENDER         VARCHAR2(4000 BYTE),
  EVAL_PENYELESAIAN   VARCHAR2(4000 BYTE),
  EVAL_PENGIRIMAN     VARCHAR2(4000 BYTE),
  EVAL_KINERJA        VARCHAR2(4000 BYTE),
  EVAL_PERNYATAAN     VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PERUBAHAN
(
  KODE_PERUBAHAN      INTEGER,
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  TGL_MULAI           DATE,
  TGL_AKHIR           DATE,
  MATA_UANG           VARCHAR2(3 BYTE),
  NILAI_KONTRAK       NUMBER(19,4),
  STATUS              VARCHAR2(2 BYTE),
  POSISI_PERSETUJUAN  VARCHAR2(50 BYTE),
  TGL_PERUBAHAN       DATE,
  KONTRAK_TIPE        VARCHAR2(50 BYTE),
  KONTRAK_TIPE_2      VARCHAR2(50 BYTE),
  NO_KONTRAK          VARCHAR2(50 BYTE),
  PERIODE_BAYAR_SEWA  INTEGER,
  UNIT_BAYAR_SEWA     VARCHAR2(50 BYTE),
  TERMIN_BAYAR_SEWA   VARCHAR2(100 BYTE),
  KET_PERUBAHAN       VARCHAR2(4000 BYTE),
  ALASAN_PERUBAHAN    VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PO
(
  KODE_PO                  VARCHAR2(50 BYTE),
  KODE_KONTRAK             VARCHAR2(50 BYTE),
  KODE_KANTOR              VARCHAR2(5 BYTE),
  NAMA_PEMBUAT             VARCHAR2(250 BYTE),
  NAMA_LENGKAP_PEMBUAT     VARCHAR2(250 BYTE),
  POSISI_PEMBUAT           VARCHAR2(50 BYTE),
  KODE_VENDOR              INTEGER,
  NAMA_VENDOR              VARCHAR2(255 BYTE),
  MATA_UANG                VARCHAR2(3 BYTE),
  TGL_MULAI                DATE,
  TGL_AKHIR                DATE,
  TGL_BUAT                 DATE,
  CATATAN_PO               VARCHAR2(1024 BYTE),
  TGL_PERSETUJUAN          DATE,
  STATUS                   VARCHAR2(2 BYTE),
  POSISI_PERSETUJUAN       VARCHAR2(50 BYTE),
  PERSENTASI_PERKEMBANGAN  INTEGER,
  STATUS_PERKEMBANGAN      VARCHAR2(2 BYTE),
  NO_BASTP                 VARCHAR2(50 BYTE),
  TGL_BASTP                DATE,
  JUDUL_BASTP              VARCHAR2(1024 BYTE),
  LAMPIRAN_BASTP           VARCHAR2(250 BYTE),
  TGL_BUAT_BASTP           DATE,
  STATUS_BASTP             VARCHAR2(2 BYTE),
  TGL_PERSETUJUAN_BASTP    DATE,
  KETERANGAN_BASTP         VARCHAR2(4000 BYTE),
  TGL_REKAM                DATE,
  PETUGAS_REKAM            VARCHAR2(10 BYTE),
  TGL_UBAH                 DATE,
  PETUGAS_UBAH             VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PO_ITEM
(
  KODE_PO_ITEM          INTEGER,
  KODE_PO               VARCHAR2(50 BYTE),
  KODE_KONTRAK          VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(255 BYTE),
  HARGA                 NUMBER(19,4),
  QTY                   NUMBER(18),
  SATUAN                VARCHAR2(10 BYTE),
  SUB_TOTAL             NUMBER(19,4),
  KETERANGAN_LENGKAP    VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PO_KOMENTAR
(
  KODE_KOMENTAR       INTEGER,
  KODE_PO             VARCHAR2(50 BYTE),
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(150 BYTE),
  NAMA_KOMENTAR       VARCHAR2(150 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_PO_PERKEMBANGAN
(
  KODE_PERKEMBANGAN        INTEGER,
  KODE_PO                  VARCHAR2(50 BYTE),
  KODE_KONTRAK             VARCHAR2(50 BYTE),
  KODE_KANTOR              VARCHAR2(5 BYTE),
  TGL_PERKEMBANGAN         DATE,
  TGL_BUAT                 DATE,
  PEMBUAT                  VARCHAR2(50 BYTE),
  NAMA_PEMBUAT             VARCHAR2(250 BYTE),
  STATUS                   VARCHAR2(2 BYTE),
  PERSENTASI_PERKEMBANGAN  INTEGER,
  POSISI_PERSETUJUAN       INTEGER,
  KETERANGAN               VARCHAR2(4000 BYTE),
  TGL_REKAM                DATE,
  PETUGAS_REKAM            VARCHAR2(10 BYTE),
  TGL_UBAH                 DATE,
  PETUGAS_UBAH             VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_TERMIN_KOMENTAR
(
  KODE_KOMENTAR       INTEGER,
  KODE_TERMIN         INTEGER,
  KODE_KONTRAK        VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        INTEGER,
  NAMA_JABATAN        VARCHAR2(150 BYTE),
  NAMA_KOMENTAR       VARCHAR2(150 BYTE),
  TGL_KOMENTAR        DATE,
  STATUS_KOMENTAR     VARCHAR2(5 BYTE),
  TANGGAPAN_KOMENTAR  VARCHAR2(100 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  KOMENTAR            VARCHAR2(4000 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_TERMIN_KONTRAK
(
  KODE_TERMIN              INTEGER,
  KODE_KONTRAK             VARCHAR2(50 BYTE),
  KODE_KANTOR              VARCHAR2(5 BYTE),
  TERMIN                   VARCHAR2(255 BYTE),
  KETERANGAN               VARCHAR2(1024 BYTE),
  PERSENTASI               NUMBER(18),
  TGL_BAYAR                DATE,
  PERSENTASI_PERKEMBANGAN  INTEGER,
  STATUS_PERKEMBANGAN      VARCHAR2(2 BYTE),
  NO_BASTP                 VARCHAR2(50 BYTE),
  TGL_BASTP                DATE,
  JUDUL_BASTP              VARCHAR2(1024 BYTE),
  LAMPIRAN_BASTP           VARCHAR2(250 BYTE),
  TGL_BUAT_BASTP           DATE,
  STATUS_BASTP             CHAR(1 BYTE),
  POSISI_PERSETUJUAN       INTEGER,
  DP_PERSENTASI            INTEGER,
  KETERANGAN_BASTP         VARCHAR2(4000 BYTE),
  TGL_REKAM                DATE,
  PETUGAS_REKAM            VARCHAR2(10 BYTE),
  TGL_UBAH                 DATE,
  PETUGAS_UBAH             VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_TERMIN_PERKEMBANGAN
(
  KODE_PERKEMBANGAN  INTEGER,
  KODE_TERMIN        INTEGER,
  KODE_KONTRAK       VARCHAR2(50 BYTE),
  KODE_KANTOR        VARCHAR2(5 BYTE),
  TGL_PERKEMBANGAN   DATE,
  PERSENTASI         INTEGER,
  STATUS             VARCHAR2(2 BYTE),
  KETERANGAN         VARCHAR2(4000 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_KTR_TERMIN_PERUBAHAN
(
  KODE_PERUBAHAN  INTEGER,
  KODE_TERMIN     INTEGER,
  KODE_KONTRAK    VARCHAR2(50 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  TERMIN          VARCHAR2(255 BYTE),
  KETERANGAN      VARCHAR2(1024 BYTE),
  PERSENTASI      NUMBER(18),
  TGL_BAYAR       DATE,
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_MS_KELOMPOK_PANITIA
(
  KODE_PANITIA   INTEGER,
  NAMA_PANITIA   VARCHAR2(100 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(20 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(20 BYTE)
);


CREATE TABLE EP_MS_MENU
(
  KODE_MENU        VARCHAR2(50 BYTE),
  NAMA_MENU        VARCHAR2(255 BYTE),
  CONTROLLER       VARCHAR2(255 BYTE),
  KODE_MENU_INDUK  VARCHAR2(50 BYTE),
  STATUS           VARCHAR2(1 BYTE),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(20 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(20 BYTE)
);


CREATE TABLE EP_MS_MENU_JABATAN
(
  KODE_MENU      VARCHAR2(50 BYTE),
  KODE_JABATAN   VARCHAR2(10 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(20 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(20 BYTE)
);


CREATE TABLE EP_MS_OTORISASI
(
  KODE_OTORISASI        INTEGER,
  KODE_JABATAN          VARCHAR2(10 BYTE),
  NILAI_MAKS_OTORISASI  NUMBER(19,4),
  MATA_UANG             VARCHAR2(3 BYTE),
  KODE_OTORISASI_INDUK  INTEGER,
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(20 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(20 BYTE)
);


CREATE TABLE EP_NOMORURUT
(
  KODE_NOMORURUT  VARCHAR2(20 BYTE),
  KODE_KANTOR     VARCHAR2(5 BYTE),
  NOMORURUT       INTEGER,
  CONSTRAINT EP_NOMORURUT_PK
  PRIMARY KEY
  (KODE_NOMORURUT, KODE_KANTOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_PGD_AKTIFITAS_TENDER
(
  KODE_AKTIFITAS  INTEGER,
  NAMA_AKTIFITAS  VARCHAR2(64 BYTE),
  KETERANGAN      VARCHAR2(1024 BYTE),
  FORM            VARCHAR2(64 BYTE),
  URUTAN          INTEGER,
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_BATAS_TENDER
(
  KODE_BATAS        INTEGER,
  KODE_KANTOR       VARCHAR2(5 BYTE),
  BATAS_PENUNJUKAN  NUMBER(18),
  BATAS_PEMILIHAN   NUMBER(18),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_DOKUMEN
(
  KODE_DOKUMEN   INTEGER,
  KODE_TENDER    VARCHAR2(50 BYTE),
  KODE_KANTOR    VARCHAR2(50 BYTE),
  KODE_KATEGORI  INTEGER,
  KETERANGAN     VARCHAR2(1024 BYTE),
  NAMA_FILE      VARCHAR2(64 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_DOKUMEN_KATEGORI
(
  KODE_KATEGORI  INTEGER,
  NAMA           VARCHAR2(64 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_DOKUMEN_PERENCANAAN
(
  KODE_DOKUMEN      INTEGER,
  KODE_PERENCANAAN  INTEGER,
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KODE_KATEGORI     INTEGER,
  KETERANGAN        VARCHAR2(1024 BYTE),
  NAMA_FILE         VARCHAR2(150 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_EVALUASI_MODEL
(
  KODE_EVALUASI  INTEGER,
  TIPE           INTEGER,
  NAMA           VARCHAR2(64 BYTE),
  TINGKAT        NUMBER(15),
  BOBOT_TEKNIS   NUMBER(15),
  BOBOT_HARGA    NUMBER(15),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_EVALUASI_MODEL_DETAIL
(
  KODE_EVAL_DETAIL  INTEGER,
  KODE_EVALUASI     INTEGER,
  ITEM              VARCHAR2(256 BYTE),
  BOBOT             NUMBER(15),
  STATUS            VARCHAR2(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_ITEM_PENAWARAN
(
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_VENDOR           INTEGER,
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(1024 BYTE),
  JUMLAH                INTEGER,
  HARGA                 NUMBER(19,4),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_ITEM_PENAWARAN_HIS
(
  KODE_ITEM_PENAWARAN   INTEGER,
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_VENDOR           INTEGER,
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(1024 BYTE),
  JUMLAH                INTEGER,
  HARGA                 NUMBER(19,4),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_ITEM_PERENCANAAN
(
  KODE_PERENCANAAN      INTEGER,
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  TIPE_ITEM             CHAR(1 BYTE),
  KETERANGAN_ITEM       VARCHAR2(256 BYTE),
  SATUAN                VARCHAR2(64 BYTE),
  MATA_UANG             VARCHAR2(3 BYTE),
  JUMLAH                INTEGER,
  HARGA                 NUMBER(18,2),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_ITEM_TENDER
(
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(1024 BYTE),
  JUMLAH                INTEGER,
  UNIT                  VARCHAR2(50 BYTE),
  HARGA                 NUMBER(19,4),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_KOMENTAR_EVALUASI
(
  KODE_KOMENTAR  INTEGER,
  KODE_TENDER    VARCHAR2(50 BYTE),
  KODE_KANTOR    VARCHAR2(5 BYTE),
  NAMA           VARCHAR2(64 BYTE),
  KODE_VENDOR    VARCHAR2(10 BYTE),
  NAMA_VENDOR    VARCHAR2(256 BYTE),
  TANGGAL        DATE,
  "MODE"         CHAR(1 BYTE),
  KOMENTAR       VARCHAR2(4000 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_KOMENTAR_TENDER
(
  KODE_KOMENTAR       INTEGER,
  KODE_TENDER         VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_JABATAN        VARCHAR2(10 BYTE),
  JABATAN             VARCHAR2(64 BYTE),
  NAMA                VARCHAR2(64 BYTE),
  KODE_AKTIFITAS      INTEGER,
  AKTIFITAS           VARCHAR2(64 BYTE),
  TGL_MULAI           DATE,
  TGL_BERAKHIR        DATE,
  KODE_RESPON_TENDER  INTEGER,
  RESPON              VARCHAR2(64 BYTE),
  KOMENTAR            VARCHAR2(1024 BYTE),
  LAMPIRAN            VARCHAR2(256 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PEMBELIAN
(
  KODE_TENDER    VARCHAR2(50 BYTE),
  KODE_KANTOR    VARCHAR2(5 BYTE),
  NAMA_VENDOR    VARCHAR2(500 BYTE),
  PPN            INTEGER,
  TGL_PEMBELIAN  DATE,
  KETERANGAN     VARCHAR2(4000 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PEMBELIAN_DETAIL
(
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  KODE_BARANG_JASA      VARCHAR2(50 BYTE),
  KODE_SUB_BARANG_JASA  VARCHAR2(50 BYTE),
  KETERANGAN            VARCHAR2(1024 BYTE),
  JUMLAH                INTEGER,
  HARGA                 NUMBER(19,4),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PENAWARAN
(
  KODE_TENDER       VARCHAR2(50 BYTE),
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KODE_VENDOR       INTEGER,
  NO_PENAWARAN      VARCHAR2(64 BYTE),
  TIPE              VARCHAR2(1 BYTE),
  BID_BOND          NUMBER(19,4),
  LOCAL_CONTENT     NUMBER(7),
  WAKTU_PENGIRIMAN  INTEGER,
  UNIT              VARCHAR2(1 BYTE),
  BERLAKU_HINGGA    DATE,
  LAMPIRAN          VARCHAR2(255 BYTE),
  KETERANGAN        VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PENAWARAN_HIS
(
  KODE_PENAWARAN    INTEGER,
  KODE_TENDER       VARCHAR2(50 BYTE),
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KODE_VENDOR       INTEGER,
  NO_PENAWARAN      VARCHAR2(64 BYTE),
  TIPE              VARCHAR2(1 BYTE),
  BID_BOND          NUMBER(19,4),
  LOCAL_CONTENT     NUMBER(7),
  WAKTU_PENGIRIMAN  INTEGER,
  UNIT              VARCHAR2(1 BYTE),
  BERLAKU_HINGGA    DATE,
  LAMPIRAN          VARCHAR2(255 BYTE),
  KETERANGAN        VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PENAWARAN_LOG
(
  KODE_LOG_PENAWARAN  INTEGER,
  KODE_TENDER         VARCHAR2(50 BYTE),
  KODE_KANTOR         VARCHAR2(5 BYTE),
  KODE_VENDOR         INTEGER,
  RESPON              VARCHAR2(50 BYTE),
  TGL_RESPON          DATE,
  IP_RESPON           VARCHAR2(50 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PENAWARAN_TEKNIS
(
  KODE_TENDER        VARCHAR2(50 BYTE),
  KODE_KANTOR        VARCHAR2(5 BYTE),
  KODE_VENDOR        INTEGER,
  KETERANGAN         VARCHAR2(256 BYTE),
  BERAT              NUMBER(15),
  STATUS_CEK         INTEGER,
  VENDOR_CEK         INTEGER,
  NILAI              NUMBER(15),
  KETERANGAN_VENDOR  VARCHAR2(4000 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERENCANAAN
(
  KODE_PERENCANAAN        INTEGER,
  KODE_KANTOR             VARCHAR2(5 BYTE),
  JUDUL_PEKERJAAN         VARCHAR2(255 BYTE),
  LINGKUP_PEKERJAAN       VARCHAR2(1024 BYTE),
  PERENCANA               VARCHAR2(64 BYTE),
  KODE_PERENCANA          INTEGER,
  STATUS                  INTEGER,
  RENCANA_KEBUTUHAN       VARCHAR2(6 BYTE),
  RENCANA_PELAKSANAAN     VARCHAR2(6 BYTE),
  KODE_LOKASI_PENGIRIMAN  INTEGER,
  LOKASI_PENGIRIMAN       VARCHAR2(255 BYTE),
  SWAKELOLA               INTEGER,
  PENATA_PERENCANAAN      VARCHAR2(64 BYTE),
  KODE_JABATAN_PENATA     INTEGER,
  MATA_UANG               VARCHAR2(3 BYTE),
  KETERANGAN_TAMBAHAN     VARCHAR2(255 BYTE),
  KOMENTAR                VARCHAR2(255 BYTE),
  KODE_AKTIFITAS          INTEGER,
  PPN                     INTEGER,
  KODE_RENCANA            INTEGER,
  TGL_DISETUJUI           DATE,
  KODE_JABATAN_PENYETUJU  INTEGER,
  TGL_REKAM               DATE,
  PETUGAS_REKAM           VARCHAR2(10 BYTE),
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERENCANAAN_ANGGARAN
(
  KODE_PERENCANAAN   INTEGER,
  KODE_KANTOR        VARCHAR2(5 BYTE),
  MATA_ANGGARAN      VARCHAR2(10 BYTE),
  SUB_MATA_ANGGARAN  VARCHAR2(10 BYTE),
  PAGU_ANGGARAN      NUMBER(18,2),
  SISA_ANGGARAN      NUMBER(18,2),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERENCANAAN_HIS
(
  KODE_HIS_PERENCANAAN    INTEGER,
  KODE_PERENCANAAN        INTEGER,
  KODE_KANTOR             VARCHAR2(5 BYTE),
  JUDUL_PEKERJAAN         VARCHAR2(255 BYTE),
  LINGKUP_PEKERJAAN       VARCHAR2(1024 BYTE),
  PERENCANA               VARCHAR2(64 BYTE),
  KODE_PERENCANA          INTEGER,
  STATUS                  INTEGER,
  RENCANA_KEBUTUHAN       VARCHAR2(6 BYTE),
  RENCANA_PELAKSANAAN     VARCHAR2(6 BYTE),
  KODE_LOKASI_PENGIRIMAN  INTEGER,
  LOKASI_PENGIRIMAN       VARCHAR2(255 BYTE),
  SWAKELOLA               INTEGER,
  PENATA_PERENCANAAN      VARCHAR2(64 BYTE),
  KODE_JABATAN_PENATA     INTEGER,
  MATA_UANG               VARCHAR2(3 BYTE),
  KETERANGAN_TAMBAHAN     VARCHAR2(255 BYTE),
  KOMENTAR                VARCHAR2(255 BYTE),
  STATUS_AKTIFITAS        INTEGER,
  PPN                     INTEGER,
  KODE_RENCANA            INTEGER,
  TGL_DISETUJUI           DATE,
  KODE_JABATAN_PENYETUJU  INTEGER,
  TGL_REKAM               DATE,
  PETUGAS_REKAM           VARCHAR2(10 BYTE),
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERSIAPAN_TENDER
(
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  METODE_TENDER         INTEGER,
  METODE_SUBMISSION     INTEGER,
  METODE_EVALUASI       INTEGER,
  TGL_PEMBUKAAN_REG     DATE,
  TGL_PENUTUPAN_REG     DATE,
  TGL_PRE_LELANG        DATE,
  LOKASI_PRE_LELANG     VARCHAR2(150 BYTE),
  TGL_PENUTUPAN_PEN     DATE,
  TGL_LELANG_TEKNIS     DATE,
  TGL_LELANG_KOMODITI   DATE,
  KODE_KANTOR_PEMINTA   VARCHAR2(5 BYTE),
  CATATAN_KE_VENDOR     VARCHAR2(1024 BYTE),
  URUTAN                VARCHAR2(1 BYTE),
  TGL_PEMBUKAAN_KUA     DATE,
  TGL_PENUTUPAN_KUA     DATE,
  KODE_EVALUASI         INTEGER,
  KETERANGAN_EVALUASI   VARCHAR2(64 BYTE),
  KODE_PANITIA          INTEGER,
  NAMA_PANITIA          VARCHAR2(100 BYTE),
  KODE_PRE_KUALIFIKASI  INTEGER,
  NAMA_PRE_KUALIFIKASI  VARCHAR2(64 BYTE),
  TGL_PEMBUKAAN_LELANG  DATE,
  TGL_AANWIJZING2       DATE,
  LOKASI_AANWIJZING2    VARCHAR2(150 BYTE),
  JUSTIFIKASI           VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERSIAPAN_TENDER_LOG
(
  KODE_LOG_PERSIAPAN    INTEGER,
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(5 BYTE),
  METODE_TENDER         INTEGER,
  METODE_SUBMISSION     INTEGER,
  METODE_EVALUASI       INTEGER,
  TGL_PEMBUKAAN_REG     DATE,
  TGL_PENUTUPAN_REG     DATE,
  TGL_PRE_LELANG        DATE,
  LOKASI_PRE_LELANG     VARCHAR2(150 BYTE),
  TGL_PENUTUPAN_PEN     DATE,
  TGL_LELANG_TEKNIS     DATE,
  TGL_LELANG_KOMODITI   DATE,
  KODE_KANTOR_PEMINTA   VARCHAR2(5 BYTE),
  CATATAN_KE_VENDOR     VARCHAR2(1024 BYTE),
  URUTAN                VARCHAR2(1 BYTE),
  TGL_PEMBUKAAN_KUA     DATE,
  TGL_PENUTUPAN_KUA     DATE,
  KODE_EVALUASI         INTEGER,
  KETERANGAN_EVALUASI   VARCHAR2(64 BYTE),
  KODE_PANITIA          INTEGER,
  NAMA_PANITIA          VARCHAR2(100 BYTE),
  KODE_PRE_KUALIFIKASI  INTEGER,
  NAMA_PRE_KUALIFIKASI  VARCHAR2(64 BYTE),
  TGL_PEMBUKAAN_LELANG  DATE,
  TGL_AANWIJZING2       DATE,
  LOKASI_AANWIJZING2    VARCHAR2(150 BYTE),
  JUSTIFIKASI           VARCHAR2(4000 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PERUBAHAN_PERENCANAAN
(
  KODE_PERUBAHAN    INTEGER,
  KODE_PERENCANAAN  INTEGER,
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KETERANGAN        VARCHAR2(2000 BYTE),
  NILAI             NUMBER(18,2),
  LAMPIRAN          VARCHAR2(150 BYTE),
  KODE_JABATAN      VARCHAR2(10 BYTE),
  NAMA_JABATAN      VARCHAR2(100 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_PESAN_LELANG
(
  KODE_PESAN_LELANG  INTEGER,
  KODE_TENDER        VARCHAR2(50 BYTE),
  KODE_KANTOR        VARCHAR2(5 BYTE),
  KODE_AKTIFITAS     INTEGER,
  KODE_VENDOR        VARCHAR2(10 BYTE),
  TANGGAL            DATE,
  "MODE"             VARCHAR2(1 BYTE),
  PESAN              VARCHAR2(4000 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(10 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_RESPON_TENDER
(
  KODE_RESPON_TENDER  INTEGER,
  KODE_AKTIFITAS      INTEGER,
  NAMA                VARCHAR2(64 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_TENDER
(
  KODE_TENDER          VARCHAR2(50 BYTE),
  KODE_KANTOR          VARCHAR2(5 BYTE),
  KODE_PERENCANAAN     INTEGER,
  KODE_TENDER_SEBELUM  VARCHAR2(50 BYTE),
  KODE_TENDER_SESUDAH  VARCHAR2(50 BYTE),
  NAMA_PEMOHON         VARCHAR2(64 BYTE),
  KODE_JAB_PEMOHON     VARCHAR2(10 BYTE),
  NAMA_PERENCANA       VARCHAR2(64 BYTE),
  KODE_JAB_PERENCANA   VARCHAR2(10 BYTE),
  NAMA_PELAKSANA       VARCHAR2(64 BYTE),
  KODE_JAB_PELAKSANA   VARCHAR2(10 BYTE),
  TGL_PEMBUATAN        DATE,
  JUDUL_PEKERJAAN      VARCHAR2(1024 BYTE),
  LINGKUP_PEKERJAAN    VARCHAR2(1024 BYTE),
  WAKTU_PENGIRIMAN     INTEGER,
  UNIT_PENGIRIMAN      INTEGER,
  NAMA_PEMBELI         VARCHAR2(64 BYTE),
  KODE_JAB_PEMBELI     VARCHAR2(10 BYTE),
  MATA_UANG            VARCHAR2(3 BYTE),
  TIPE_KONTRAK         VARCHAR2(64 BYTE),
  NAMA_JAB_PESERTA     VARCHAR2(64 BYTE),
  KODE_JAB_PESERTA     VARCHAR2(10 BYTE),
  PEMBUATAN_KONTRAK    VARCHAR2(1 BYTE),
  STATUS               INTEGER,
  TGL_SELESAI          DATE,
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE)
);


CREATE TABLE EP_PGD_TENDER_VENDOR_STATUS
(
  KODE_TENDER           VARCHAR2(50 BYTE),
  KODE_KANTOR           VARCHAR2(50 BYTE),
  KODE_VENDOR           INTEGER,
  STATUS                INTEGER,
  TEKNIKAL_STATUS       INTEGER,
  KETERANGAN_TEKNIKAL   VARCHAR2(256 BYTE),
  KOMERSIAL_STATUS      INTEGER,
  KETERANGAN_KOMERSIAL  VARCHAR2(256 BYTE),
  PEMENANG              VARCHAR2(1 BYTE),
  NEGOSIASI             VARCHAR2(1 BYTE),
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE)
);


CREATE TABLE EP_VENDOR_DELISTING
(
  KODE_DELISTING  INTEGER,
  KODE_ROUTE_DEF  INTEGER,
  KODE_VENDOR     INTEGER,
  NAMA_VENDOR     VARCHAR2(255 BYTE),
  KODE_WILAYAH    INTEGER,
  NAMA_WILAYAH    VARCHAR2(255 BYTE),
  KODE_GROUP      VARCHAR2(50 BYTE),
  NAMA_GROUP      VARCHAR2(255 BYTE),
  KLASIFIKASI     VARCHAR2(50 BYTE),
  TERDAFTAR       CHAR(1 BYTE),
  TIPE_KOMODITI   CHAR(1 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_DELISTING_PK
  PRIMARY KEY
  (KODE_DELISTING)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_DOKUMEN_REF
(
  KODE_DOKUMEN_REF  INTEGER,
  NO                VARCHAR2(5 BYTE),
  NAMA              VARCHAR2(255 BYTE),
  TIPE              CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_DOKUMEN_REF_PK
  PRIMARY KEY
  (KODE_DOKUMEN_REF)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HALAMAN
(
  NO_HALAMAN           VARCHAR2(2 BYTE),
  NAMA_HALAMAN         VARCHAR2(255 BYTE),
  HALAMAN_SELANJUTNYA  VARCHAR2(255 BYTE),
  NOTE                 VARCHAR2(50 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HALAMAN_PK
  PRIMARY KEY
  (NO_HALAMAN)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_KOMENTAR_DETAIL
(
  KODE_KOMENTAR  INTEGER,
  KODE_JABATAN   INTEGER,
  NAMA_JABATAN   VARCHAR2(64 BYTE),
  NAMA           VARCHAR2(64 BYTE),
  AKTIFITAS      VARCHAR2(64 BYTE),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  TANGGAPAN      VARCHAR2(64 BYTE),
  KOMENTAR       VARCHAR2(1024 BYTE),
  STATUS         VARCHAR2(10 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_KOMENTAR_DETAIL_PK
  PRIMARY KEY
  (KODE_KOMENTAR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_ROUTE_DEF
(
  KODE_ROUTE_DEF  INTEGER,
  NAMA_ROUTE_DEF  VARCHAR2(50 BYTE),
  STATUS          VARCHAR2(10 BYTE),
  KODE_VENDOR     INTEGER,
  NAMA_VENDOR     VARCHAR2(500 BYTE),
  TGL_BUAT        DATE,
  TGL_SELESAI     DATE,
  URL             VARCHAR2(200 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_ROUTE_DEF_PK
  PRIMARY KEY
  (KODE_ROUTE_DEF)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_ROUTING
(
  KODE_ROUTING    INTEGER,
  KODE_ROUTE_DEF  INTEGER,
  KODE_JABATAN    INTEGER,
  NAMA_JABATAN    VARCHAR2(64 BYTE),
  NAMA            VARCHAR2(64 BYTE),
  AKTIFITAS       VARCHAR2(64 BYTE),
  TGL_MULAI       DATE,
  TGL_BERAKHIR    DATE,
  TANGGAPAN       VARCHAR2(64 BYTE),
  KOMENTAR        VARCHAR2(1024 BYTE),
  STATUS          VARCHAR2(10 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_ROUTING_PK
  PRIMARY KEY
  (KODE_ROUTING)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_ROUTING_FK 
  FOREIGN KEY (KODE_ROUTE_DEF) 
  REFERENCES EP_VENDOR_ROUTE_DEF (KODE_ROUTE_DEF)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_SESSION
(
  KODE_SESSION   VARCHAR2(50 BYTE),
  ALAMAT_IP      VARCHAR2(50 BYTE),
  TGL_TERAKHIR   DATE,
  KODE_LOGIN     VARCHAR2(50 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_SESSION_PK1
  PRIMARY KEY
  (KODE_SESSION, ALAMAT_IP)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_STATUS_REGISTRASI
(
  KODE_STATUS_REG   INTEGER,
  KODE2_STATUS_REG  VARCHAR2(3 BYTE),
  NAMA_STATUS_REG   VARCHAR2(200 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_SESSION_PK
  PRIMARY KEY
  (KODE_STATUS_REG)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP
(
  KODE_VENDOR             INTEGER,
  NAMA_VENDOR             VARCHAR2(50 BYTE),
  KODE_LOGIN              VARCHAR2(50 BYTE),
  PASSWRD                 VARCHAR2(255 BYTE),
  ALAMAT_EMAIL            VARCHAR2(255 BYTE),
  AWALAN                  VARCHAR2(50 BYTE),
  AWALAN_LAIN             VARCHAR2(50 BYTE),
  AKHIRAN                 VARCHAR2(50 BYTE),
  AKHIRAN_LAIN            VARCHAR2(50 BYTE),
  ALAMAT                  VARCHAR2(512 BYTE),
  KOTA                    VARCHAR2(512 BYTE),
  PROPINSI                VARCHAR2(512 BYTE),
  KODE_POS                VARCHAR2(50 BYTE),
  NEGARA                  VARCHAR2(255 BYTE),
  NO_TELP                 VARCHAR2(50 BYTE),
  WEBSITE                 VARCHAR2(512 BYTE),
  NO_DOMISILI             VARCHAR2(50 BYTE),
  TGL_DOMISILI            DATE,
  KADALUARSA_DOMISILI     DATE,
  NAMA_KONTAK             VARCHAR2(255 BYTE),
  JABATAN_KONTAK          VARCHAR2(255 BYTE),
  NO_TELP_KONTAK          VARCHAR2(50 BYTE),
  EMAIL_KONTAK            VARCHAR2(100 BYTE),
  NPP                     VARCHAR2(50 BYTE),
  TGL_NPP                 DATE,
  NO_NPWP                 VARCHAR2(50 BYTE),
  ALAMAT_NPWP             VARCHAR2(255 BYTE),
  KOTA_NPWP               VARCHAR2(100 BYTE),
  PROPINSI_NPWP           VARCHAR2(100 BYTE),
  KODE_POS_NPWP           VARCHAR2(50 BYTE),
  PKP_NPWP                VARCHAR2(50 BYTE),
  NO_PKP_NPWP             VARCHAR2(100 BYTE),
  TIPE_VENDOR             VARCHAR2(100 BYTE),
  TIPE_SIUP_IUJK          VARCHAR2(50 BYTE),
  SIUP_DITERBITKAN_OLEH   VARCHAR2(255 BYTE),
  NO_SIUP                 VARCHAR2(50 BYTE),
  TIPE_SIUP               VARCHAR2(50 BYTE),
  DARI_TGL_SIUP           DATE,
  SAMPAI_TGL_SIUP         DATE,
  TDP_ISSUED_BY           VARCHAR2(255 BYTE),
  NO_TDP                  VARCHAR2(50 BYTE),
  DARI_TGL_TDP            DATE,
  SAMPAI_TGL_TDP          DATE,
  AGEN_PENERBIT           VARCHAR2(255 BYTE),
  DARI_AGEN               DATE,
  HINGGA_AGEN             DATE,
  PENERBIT_IMP            VARCHAR2(255 BYTE),
  DARI_IMP                DATE,
  KE_IMP                  DATE,
  ATT_ORG                 VARCHAR2(50 BYTE),
  MATA_UANG_MODAL_DASAR   VARCHAR2(3 BYTE),
  MODAL_DASAR             NUMBER(19,4),
  MATA_UANG_MODAL_SETOR   VARCHAR2(3 BYTE),
  MODAL_SETOR             NUMBER(19,4),
  MATA_UANG_ASSET_DASAR   VARCHAR2(3 BYTE),
  ASSET_DASAR             NUMBER(19,4),
  MATA_UANG_LAPORAN_KEU   VARCHAR2(3 BYTE),
  TAHUN_LAPORAN_KEU       INTEGER,
  TIPE_LAPORAN_KEU        VARCHAR2(50 BYTE),
  ASSET_LAPORAN_KEU       NUMBER(19,4),
  HUTANG_LAPORAN_KEU      NUMBER(19,4),
  PENDAPATAN_LAPORAN_KEU  NUMBER(19,4),
  LABA_LAPORAN_KEU        NUMBER(19,4),
  GOLONGAN_KEUANGAN       CHAR(1 BYTE),
  BERAKHIR_DARI           DATE,
  BERAKHIR_SAMPAI         DATE,
  DIAKHIRI_OLEH           VARCHAR2(50 BYTE),
  TGL_REKAM               DATE,
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(50 BYTE),
  STATUS                  VARCHAR2(2 BYTE),
  HALAMAN_SELANJUTNYA     VARCHAR2(255 BYTE),
  KODE_STATUS_REG         INTEGER,
  STATUS_REG              CHAR(1 BYTE),
  SESSION_ID_REG          VARCHAR2(512 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_PK
  PRIMARY KEY
  (KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_FK 
  FOREIGN KEY (KODE_STATUS_REG) 
  REFERENCES EP_VENDOR_STATUS_REGISTRASI (KODE_STATUS_REG)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_AGEN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  TGL_BUAT       DATE,
  TGL_BERAKHIR   DATE,
  NO             VARCHAR2(150 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_AGEN_PK
  PRIMARY KEY
  (NO, TIPE, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_AGEN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_AKTA
(
  KODE_VENDOR       INTEGER,
  TIPE_AKTA         VARCHAR2(50 BYTE),
  NO_AKTA           VARCHAR2(50 BYTE),
  TGL_PEMBUATAN     DATE,
  NAMA_NOTARIS      VARCHAR2(50 BYTE),
  ALAMAT_NOTARIS    VARCHAR2(255 BYTE),
  PENGESAHAN_HAKIM  DATE,
  BERITA_ACARA_NGR  DATE,
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_AKTA_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_AKTA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_AKTA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_ALAMAT
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(255 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  NO_TELP1       VARCHAR2(50 BYTE),
  NO_TELP2       VARCHAR2(50 BYTE),
  FAX            VARCHAR2(50 BYTE),
  WEBSITE        VARCHAR2(50 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_ALAMAT_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_ALAMAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_BANK
(
  KODE_VENDOR    INTEGER,
  NO_REKENING    VARCHAR2(50 BYTE),
  NAMA_REKENING  VARCHAR2(255 BYTE),
  NAMA_BANK      VARCHAR2(50 BYTE),
  CABANG         VARCHAR2(50 BYTE),
  MATA_UANG      VARCHAR2(50 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_BANK_PK
  PRIMARY KEY
  (KODE_VENDOR, NO_REKENING)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_BANK_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_BARANG
(
  KODE_VENDOR    INTEGER,
  NAMA_BARANG    VARCHAR2(255 BYTE),
  KODE_BARANG    VARCHAR2(50 BYTE),
  KETERANGAN     VARCHAR2(1024 BYTE),
  MEREK          VARCHAR2(50 BYTE),
  SUMBER         VARCHAR2(50 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_BARANG_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_BARANG)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_BARANG_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_DEWAN_DIREKSI
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NAMA           VARCHAR2(512 BYTE),
  JABATAN        VARCHAR2(255 BYTE),
  NO_TELP        VARCHAR2(50 BYTE),
  EMAIL          VARCHAR2(255 BYTE),
  NO_KTP         VARCHAR2(255 BYTE),
  NO_NPWP        VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_D_DIREKSI_PK
  PRIMARY KEY
  (JABATAN, NAMA, TIPE, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_D_DIREKSI_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_IJIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  NO             VARCHAR2(50 BYTE),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_IJIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_IJIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_INFORMASI_LAIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(100 BYTE),
  NAMA           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(50 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  KUALIFIKASI    VARCHAR2(1024 BYTE),
  HUBUNGAN       VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_INFO_LAIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_INFO_LAIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_JASA
(
  KODE_VENDOR    INTEGER,
  KODE_JASA      VARCHAR2(50 BYTE),
  NAMA_JASA      VARCHAR2(255 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_JASA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_JASA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_JASA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_KINERJA
(
  KODE_VENDOR           INTEGER,
  TANGGAL               DATE,
  KODE_TENDER           VARCHAR2(10 BYTE),
  TIPE_KOMODITI         CHAR(1 BYTE),
  KODE_KEL_JASA_BARANG  VARCHAR2(20 BYTE),
  KODE_PARAM            VARCHAR2(50 BYTE),
  NAMA_PARAM            VARCHAR2(255 BYTE),
  PILIHAN_PARAM         INTEGER,
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_KINERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_TENDER)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_KINERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_LAP_KEUANGAN
(
  KODE_VENDOR    INTEGER,
  MATA_UANG      VARCHAR2(3 BYTE),
  TAHUN          INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NILAI_ASSET    NUMBER(19,4),
  HUTANG         NUMBER(19,4),
  PENDAPATAN     NUMBER(19,4),
  LABA_BERSIH    NUMBER(19,4),
  KELAS          CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VND_TEMP_L_KEU_PK
  PRIMARY KEY
  (KODE_VENDOR, MATA_UANG, TAHUN, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VND_TEMP_L_KEU_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_PENGALAMAN
(
  KODE_VENDOR    INTEGER,
  NAMA           VARCHAR2(255 BYTE),
  NAMA_PROYEK    VARCHAR2(255 BYTE),
  MATA_UANG      VARCHAR2(3 BYTE),
  NILAI          NUMBER(19,4),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  KONTAK         VARCHAR2(255 BYTE),
  NO_KONTAK      VARCHAR2(50 BYTE),
  NO_KONTRAK     VARCHAR2(50 BYTE),
  KETERANGAN     VARCHAR2(4000 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_PENGALAMAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA, NAMA_PROYEK)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_PENGALAMAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_PERALATAN
(
  KODE_VENDOR      INTEGER,
  KATEGORI         VARCHAR2(50 BYTE),
  NAMA_PERALATAN   VARCHAR2(255 BYTE),
  SPESIFIKASI      VARCHAR2(512 BYTE),
  TAHUN_PEMBUATAN  INTEGER,
  JUMLAH           NUMBER(18),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_PERALATAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_PERALATAN)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_PERALATAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_SERTIFIKAT
(
  KODE_VENDOR     INTEGER,
  NAMA            VARCHAR2(255 BYTE),
  PENERBIT        VARCHAR2(255 BYTE),
  TIPE            VARCHAR2(50 BYTE),
  TIPE_LAIN       VARCHAR2(50 BYTE),
  BERLAKU_DARI    DATE,
  BERLAKU_HINGGA  DATE,
  NO_SERTIFIKAT   VARCHAR2(50 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_SERTIFIKAT_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_SERTIFIKAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_TENAGA_KERJA
(
  KODE_VENDOR          INTEGER,
  NAMA                 VARCHAR2(255 BYTE),
  TIPE                 VARCHAR2(50 BYTE),
  PENDIDIKAN_TERAKHIR  VARCHAR2(50 BYTE),
  KEAHLIAN             VARCHAR2(1024 BYTE),
  TAHUN_BERAKHIR       INTEGER,
  STATUS_PEGAWAI       VARCHAR2(50 BYTE),
  TIPE_PEGAWAI         VARCHAR2(50 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_TENAGA_KERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_TENAGA_KERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_TIPE
(
  KODE_VENDOR    INTEGER,
  TIPE_VENDOR    VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_TIPE_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_TIPE_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TEMP_WILAYAH
(
  KODE_WILAYAH   INTEGER,
  KODE_VENDOR    INTEGER,
  KODE2_WILAYAH  INTEGER,
  WILAYAH        VARCHAR2(255 BYTE),
  NO_SMK         VARCHAR2(50 BYTE),
  TGL_SMK        DATE,
  BERLAKU_SMK    DATE,
  STATUS_AKTIF   CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TEMP_WILAYAH_PK
  PRIMARY KEY
  (KODE_WILAYAH, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TEMP_WILAYAH_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR_TEMP (KODE_VENDOR)
  ON DELETE CASCADE
  ENABLE VALIDATE
);


CREATE TABLE KODE_TENDER
(
  KODE_KANTOR       VARCHAR2(5 BYTE),
  KODE_VENDOR       NUMBER(15),
  GRADE             NUMBER(15),
  BOBOT             NUMBER(15),
  NILAI             NUMBER(15),
  KETERANGAN        VARCHAR2(255 BYTE),
  BOBOT_HARGA       NUMBER(15),
  NILAI_HARGA       NUMBER(15),
  KETERANGAN_HARGA  VARCHAR2(255 BYTE),
  PERINGKAT         INTEGER,
  PEMENANG          INTEGER,
  PENAWARAN         CHAR(1 BYTE),
  BID_BOND          CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE)
);


CREATE TABLE MS_BARANG
(
  KODE_BARANG      VARCHAR2(3 BYTE),
  KODE_SUB_BARANG  VARCHAR2(2 BYTE),
  NAMA_BARANG      VARCHAR2(50 BYTE),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE),
  AKTIF            VARCHAR2(1 BYTE),
  CONSTRAINT MS_BARANG_PK
  PRIMARY KEY
  (KODE_BARANG, KODE_SUB_BARANG)
  ENABLE VALIDATE
);


CREATE TABLE MS_KANTOR
(
  KODE_KANTOR        VARCHAR2(5 BYTE),
  KODE_KANTOR_INDUK  VARCHAR2(5 BYTE),
  KODE_KP2LN         VARCHAR2(20 BYTE),
  KODE_KABUPATEN     NUMBER(20),
  KODE_KOTA_BPS      NUMBER(20),
  KODE_KELAS         VARCHAR2(2 BYTE),
  KODE_TIPE          VARCHAR2(2 BYTE),
  KODE_ENTITAS       VARCHAR2(20 BYTE),
  KODE_KOTA          NUMBER(20),
  TGL_EFEKTIF        DATE,
  NAMA_KANTOR        VARCHAR2(100 BYTE),
  ALAMAT             VARCHAR2(300 BYTE),
  TELEPON            VARCHAR2(20 BYTE),
  FAX                VARCHAR2(20 BYTE),
  KODE_POS           VARCHAR2(5 BYTE),
  FTP_IP             VARCHAR2(30 BYTE),
  KETERANGAN         VARCHAR2(1000 BYTE),
  STATUS_ONLINE      VARCHAR2(1 BYTE),
  AKTIF              VARCHAR2(1 BYTE),
  TGL_REKAM          DATE,
  PETUGAS_REKAM      VARCHAR2(20 BYTE),
  TGL_UBAH           DATE,
  PETUGAS_UBAH       VARCHAR2(20 BYTE),
  TGL_AKHIR          DATE,
  KODE_KANTOR_LAMA   VARCHAR2(5 BYTE),
  NO_URUT            VARCHAR2(4 BYTE),
  FTP_USER           VARCHAR2(200 BYTE),
  FTP_SANDI          VARCHAR2(200 BYTE),
  TGL_MIGRASI        DATE,
  NPWP               VARCHAR2(30 BYTE),
  CONSTRAINT MS_KANTOR_PK
  PRIMARY KEY
  (KODE_KANTOR)
  ENABLE VALIDATE
);
































































CREATE TABLE EP_VENDOR
(
  KODE_VENDOR             INTEGER,
  NAMA_VENDOR             VARCHAR2(50 BYTE),
  KODE_LOGIN              VARCHAR2(50 BYTE),
  PASSWRD                 VARCHAR2(255 BYTE),
  ALAMAT_EMAIL            VARCHAR2(255 BYTE),
  AWALAN                  VARCHAR2(50 BYTE),
  AWALAN_LAIN             VARCHAR2(50 BYTE),
  AKHIRAN                 VARCHAR2(50 BYTE),
  AKHIRAN_LAIN            VARCHAR2(50 BYTE),
  ALAMAT                  VARCHAR2(512 BYTE),
  KOTA                    VARCHAR2(512 BYTE),
  PROPINSI                VARCHAR2(512 BYTE),
  KODE_POS                VARCHAR2(50 BYTE),
  NEGARA                  VARCHAR2(255 BYTE),
  NO_TELP                 VARCHAR2(50 BYTE),
  WEBSITE                 VARCHAR2(512 BYTE),
  NO_DOMISILI             VARCHAR2(50 BYTE),
  TGL_DOMISILI            DATE,
  KADALUARSA_DOMISILI     DATE,
  NAMA_KONTAK             VARCHAR2(255 BYTE),
  JABATAN_KONTAK          VARCHAR2(255 BYTE),
  NO_TELP_KONTAK          VARCHAR2(50 BYTE),
  EMAIL_KONTAK            VARCHAR2(100 BYTE),
  NPP                     VARCHAR2(50 BYTE),
  TGL_NPP                 DATE,
  NO_NPWP                 VARCHAR2(50 BYTE),
  ALAMAT_NPWP             VARCHAR2(255 BYTE),
  KOTA_NPWP               VARCHAR2(100 BYTE),
  PROPINSI_NPWP           VARCHAR2(100 BYTE),
  KODE_POS_NPWP           VARCHAR2(50 BYTE),
  PKP_NPWP                VARCHAR2(50 BYTE),
  NO_PKP_NPWP             VARCHAR2(100 BYTE),
  TIPE_VENDOR             VARCHAR2(100 BYTE),
  TIPE_SIUP_IUJK          VARCHAR2(50 BYTE),
  SIUP_DITERBITKAN_OLEH   VARCHAR2(255 BYTE),
  NO_SIUP                 VARCHAR2(50 BYTE),
  TIPE_SIUP               VARCHAR2(50 BYTE),
  DARI_TGL_SIUP           DATE,
  SAMPAI_TGL_SIUP         DATE,
  TDP_ISSUED_BY           VARCHAR2(255 BYTE),
  NO_TDP                  VARCHAR2(50 BYTE),
  DARI_TGL_TDP            DATE,
  SAMPAI_TGL_TDP          DATE,
  AGEN_PENERBIT           VARCHAR2(255 BYTE),
  DARI_AGEN               DATE,
  HINGGA_AGEN             DATE,
  PENERBIT_IMP            VARCHAR2(255 BYTE),
  DARI_IMP                DATE,
  KE_IMP                  DATE,
  ATT_ORG                 VARCHAR2(50 BYTE),
  MATA_UANG_MODAL_DASAR   VARCHAR2(3 BYTE),
  MODAL_DASAR             NUMBER(19,4),
  MATA_UANG_MODAL_SETOR   VARCHAR2(3 BYTE),
  MODAL_SETOR             NUMBER(19,4),
  MATA_UANG_ASSET_DASAR   VARCHAR2(3 BYTE),
  ASSET_DASAR             NUMBER(19,4),
  MATA_UANG_LAPORAN_KEU   VARCHAR2(3 BYTE),
  TAHUN_LAPORAN_KEU       INTEGER,
  TIPE_LAPORAN_KEU        VARCHAR2(50 BYTE),
  ASSET_LAPORAN_KEU       NUMBER(19,4),
  HUTANG_LAPORAN_KEU      NUMBER(19,4),
  PENDAPATAN_LAPORAN_KEU  NUMBER(19,4),
  LABA_LAPORAN_KEU        NUMBER(19,4),
  GOLONGAN_KEUANGAN       CHAR(1 BYTE),
  BERAKHIR_DARI           DATE,
  BERAKHIR_SAMPAI         DATE,
  DIAKHIRI_OLEH           VARCHAR2(50 BYTE),
  TGL_REKAM               DATE,
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(50 BYTE),
  STATUS                  VARCHAR2(2 BYTE),
  HALAMAN_SELANJUTNYA     VARCHAR2(255 BYTE),
  KODE_STATUS_REG         INTEGER,
  STATUS_REG              CHAR(1 BYTE),
  SESSION_ID_REG          VARCHAR2(512 BYTE),
  CONSTRAINT EP_VENDOR_PK
  PRIMARY KEY
  (KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_FK 
  FOREIGN KEY (KODE_STATUS_REG) 
  REFERENCES EP_VENDOR_STATUS_REGISTRASI (KODE_STATUS_REG)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_AGEN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  TGL_BUAT       DATE,
  TGL_BERAKHIR   DATE,
  NO             VARCHAR2(150 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_AGEN_PK
  PRIMARY KEY
  (NO, TIPE, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_AGEN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_AKTA
(
  KODE_VENDOR       INTEGER,
  TIPE_AKTA         VARCHAR2(50 BYTE),
  NO_AKTA           VARCHAR2(50 BYTE),
  TGL_PEMBUATAN     DATE,
  NAMA_NOTARIS      VARCHAR2(50 BYTE),
  ALAMAT_NOTARIS    VARCHAR2(255 BYTE),
  PENGESAHAN_HAKIM  DATE,
  BERITA_ACARA_NGR  DATE,
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_AKTA_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_AKTA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_AKTA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_ALAMAT
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(255 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  NO_TELP1       VARCHAR2(50 BYTE),
  NO_TELP2       VARCHAR2(50 BYTE),
  FAX            VARCHAR2(50 BYTE),
  WEBSITE        VARCHAR2(50 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_ALAMAT_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_ALAMAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_BANK
(
  KODE_VENDOR    INTEGER,
  NO_REKENING    VARCHAR2(50 BYTE),
  NAMA_REKENING  VARCHAR2(255 BYTE),
  NAMA_BANK      VARCHAR2(50 BYTE),
  CABANG         VARCHAR2(50 BYTE),
  MATA_UANG      VARCHAR2(50 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_BANK_PK
  PRIMARY KEY
  (KODE_VENDOR, NO_REKENING)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_BANK_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_BARANG
(
  KODE_VENDOR    INTEGER,
  NAMA_BARANG    VARCHAR2(255 BYTE),
  KODE_BARANG    VARCHAR2(50 BYTE),
  KETERANGAN     VARCHAR2(1024 BYTE),
  MEREK          VARCHAR2(50 BYTE),
  SUMBER         VARCHAR2(50 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_BARANG_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_BARANG)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_BARANG_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_DEWAN_DIREKSI
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NAMA           VARCHAR2(512 BYTE),
  JABATAN        VARCHAR2(255 BYTE),
  NO_TELP        VARCHAR2(50 BYTE),
  EMAIL          VARCHAR2(255 BYTE),
  NO_KTP         VARCHAR2(255 BYTE),
  NO_NPWP        VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_DEWAN_DIREKSI_PK
  PRIMARY KEY
  (JABATAN, NAMA, TIPE, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_DEWAN_DIREKSI_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_DOKUMEN
(
  KODE_VENDOR       INTEGER,
  KODE_DOKUMEN_REF  INTEGER,
  STATUS            CHAR(1 BYTE),
  NOTE              VARCHAR2(4000 BYTE),
  KETERANGAN        VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_DOKUMEN_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_DOKUMEN_REF)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_DOKUMEN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_DOKUMEN_FK2 
  FOREIGN KEY (KODE_DOKUMEN_REF) 
  REFERENCES EP_VENDOR_DOKUMEN_REF (KODE_DOKUMEN_REF)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_DOKUMEN_PENDUKUNG
(
  KODE_VENDOR         INTEGER,
  KETERANGAN_DOKUMEN  VARCHAR2(100 BYTE),
  URL_DOKUMEN         VARCHAR2(1024 BYTE),
  NAMA_FILE           VARCHAR2(100 BYTE),
  TGL_REKAM           DATE,
  PETUGAS_REKAM       VARCHAR2(10 BYTE),
  TGL_UBAH            DATE,
  PETUGAS_UBAH        VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_DOKUMEN_PENDUKUNG_PK
  PRIMARY KEY
  (KODE_VENDOR, KETERANGAN_DOKUMEN)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_DOKUMEN_PENDUKUNG_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST
(
  KODE_VENDOR_HIST        INTEGER,
  KODE_VENDOR             INTEGER,
  NAMA_VENDOR             VARCHAR2(50 BYTE),
  KODE_LOGIN              VARCHAR2(50 BYTE),
  PASSWRD                 VARCHAR2(255 BYTE),
  ALAMAT_EMAIL            VARCHAR2(255 BYTE),
  AWALAN                  VARCHAR2(50 BYTE),
  AWALAN_LAIN             VARCHAR2(50 BYTE),
  AKHIRAN                 VARCHAR2(50 BYTE),
  AKHIRAN_LAIN            VARCHAR2(50 BYTE),
  ALAMAT                  VARCHAR2(512 BYTE),
  KOTA                    VARCHAR2(512 BYTE),
  PROPINSI                VARCHAR2(512 BYTE),
  KODE_POS                VARCHAR2(50 BYTE),
  NEGARA                  VARCHAR2(255 BYTE),
  NO_TELP                 VARCHAR2(50 BYTE),
  WEBSITE                 VARCHAR2(512 BYTE),
  NO_DOMISILI             VARCHAR2(50 BYTE),
  TGL_DOMISILI            DATE,
  KADALUARSA_DOMISILI     DATE,
  NAMA_KONTAK             VARCHAR2(255 BYTE),
  JABATAN_KONTAK          VARCHAR2(255 BYTE),
  NO_TELP_KONTAK          VARCHAR2(50 BYTE),
  EMAIL_KONTAK            VARCHAR2(100 BYTE),
  NPP                     VARCHAR2(50 BYTE),
  TGL_NPP                 DATE,
  NO_NPWP                 VARCHAR2(50 BYTE),
  ALAMAT_NPWP             VARCHAR2(255 BYTE),
  KOTA_NPWP               VARCHAR2(100 BYTE),
  PROPINSI_NPWP           VARCHAR2(100 BYTE),
  KODE_POS_NPWP           VARCHAR2(50 BYTE),
  PKP_NPWP                VARCHAR2(50 BYTE),
  NO_PKP_NPWP             VARCHAR2(100 BYTE),
  TIPE_VENDOR             VARCHAR2(100 BYTE),
  TIPE_SIUP_IUJK          VARCHAR2(50 BYTE),
  SIUP_DITERBITKAN_OLEH   VARCHAR2(255 BYTE),
  NO_SIUP                 VARCHAR2(50 BYTE),
  TIPE_SIUP               VARCHAR2(50 BYTE),
  DARI_TGL_SIUP           DATE,
  SAMPAI_TGL_SIUP         DATE,
  TDP_ISSUED_BY           VARCHAR2(255 BYTE),
  NO_TDP                  VARCHAR2(50 BYTE),
  DARI_TGL_TDP            DATE,
  SAMPAI_TGL_TDP          DATE,
  AGEN_PENERBIT           VARCHAR2(255 BYTE),
  DARI_AGEN               DATE,
  HINGGA_AGEN             DATE,
  PENERBIT_IMP            VARCHAR2(255 BYTE),
  DARI_IMP                DATE,
  KE_IMP                  DATE,
  ATT_ORG                 VARCHAR2(50 BYTE),
  MATA_UANG_MODAL_DASAR   VARCHAR2(3 BYTE),
  MODAL_DASAR             NUMBER(19,4),
  MATA_UANG_MODAL_SETOR   VARCHAR2(3 BYTE),
  MODAL_SETOR             NUMBER(19,4),
  MATA_UANG_ASSET_DASAR   VARCHAR2(3 BYTE),
  ASSET_DASAR             NUMBER(19,4),
  MATA_UANG_LAPORAN_KEU   VARCHAR2(3 BYTE),
  TAHUN_LAPORAN_KEU       INTEGER,
  TIPE_LAPORAN_KEU        VARCHAR2(50 BYTE),
  ASSET_LAPORAN_KEU       NUMBER(19,4),
  HUTANG_LAPORAN_KEU      NUMBER(19,4),
  PENDAPATAN_LAPORAN_KEU  NUMBER(19,4),
  LABA_LAPORAN_KEU        NUMBER(19,4),
  GOLONGAN_KEUANGAN       CHAR(1 BYTE),
  BERAKHIR_DARI           DATE,
  BERAKHIR_SAMPAI         DATE,
  DIAKHIRI_OLEH           VARCHAR2(50 BYTE),
  TGL_REKAM               DATE,
  TGL_UBAH                DATE,
  PETUGAS_UBAH            VARCHAR2(50 BYTE),
  STATUS                  VARCHAR2(2 BYTE),
  HALAMAN_SELANJUTNYA     VARCHAR2(255 BYTE),
  KODE_STATUS_REG         INTEGER,
  STATUS_REG              CHAR(1 BYTE),
  SESSION_ID_REG          VARCHAR2(512 BYTE),
  CONSTRAINT EP_VENDOR_HIST_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_FK 
  FOREIGN KEY (KODE_STATUS_REG) 
  REFERENCES EP_VENDOR_STATUS_REGISTRASI (KODE_STATUS_REG)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_AGEN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE              VARCHAR2(50 BYTE),
  PENERBIT          VARCHAR2(250 BYTE),
  TGL_BUAT          DATE,
  TGL_BERAKHIR      DATE,
  NO                VARCHAR2(150 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_AGEN_PK
  PRIMARY KEY
  (NO, TIPE, KODE_VENDOR, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_AGEN_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_AKTA
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE_AKTA         VARCHAR2(50 BYTE),
  NO_AKTA           VARCHAR2(50 BYTE),
  TGL_PEMBUATAN     DATE,
  NAMA_NOTARIS      VARCHAR2(50 BYTE),
  ALAMAT_NOTARIS    VARCHAR2(255 BYTE),
  PENGESAHAN_HAKIM  DATE,
  BERITA_ACARA_NGR  DATE,
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_AKTA_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_AKTA, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_AKTA_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_ALAMAT
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE              VARCHAR2(255 BYTE),
  ALAMAT            VARCHAR2(255 BYTE),
  KOTA              VARCHAR2(50 BYTE),
  NEGARA            VARCHAR2(255 BYTE),
  KODE_POS          VARCHAR2(50 BYTE),
  NO_TELP1          VARCHAR2(50 BYTE),
  NO_TELP2          VARCHAR2(50 BYTE),
  FAX               VARCHAR2(50 BYTE),
  WEBSITE           VARCHAR2(50 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_ALAMAT_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_ALAMAT_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_BANK
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  NO_REKENING       VARCHAR2(50 BYTE),
  NAMA_REKENING     VARCHAR2(255 BYTE),
  NAMA_BANK         VARCHAR2(50 BYTE),
  CABANG            VARCHAR2(50 BYTE),
  MATA_UANG         VARCHAR2(50 BYTE),
  ALAMAT            VARCHAR2(255 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_BANK_PK
  PRIMARY KEY
  (KODE_VENDOR, NO_REKENING, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_BANK_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_BARANG
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  NAMA_BARANG       VARCHAR2(255 BYTE),
  KODE_BARANG       VARCHAR2(50 BYTE),
  KETERANGAN        VARCHAR2(1024 BYTE),
  MEREK             VARCHAR2(50 BYTE),
  SUMBER            VARCHAR2(50 BYTE),
  TIPE              VARCHAR2(50 BYTE),
  TERDAFTAR         CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_BARANG_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_BARANG, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_BARANG_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_DEWAN_DIREKSI
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE              VARCHAR2(50 BYTE),
  NAMA              VARCHAR2(512 BYTE),
  JABATAN           VARCHAR2(255 BYTE),
  NO_TELP           VARCHAR2(50 BYTE),
  EMAIL             VARCHAR2(255 BYTE),
  NO_KTP            VARCHAR2(255 BYTE),
  NO_NPWP           VARCHAR2(255 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_D_DIREKSI_PK
  PRIMARY KEY
  (JABATAN, NAMA, TIPE, KODE_VENDOR, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_D_DIREKSI_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_IJIN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE              VARCHAR2(50 BYTE),
  PENERBIT          VARCHAR2(250 BYTE),
  NO                VARCHAR2(50 BYTE),
  TGL_MULAI         DATE,
  TGL_BERAKHIR      DATE,
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_IJIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_IJIN_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_INFORMASI_LAIN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE              VARCHAR2(100 BYTE),
  NAMA              VARCHAR2(255 BYTE),
  ALAMAT            VARCHAR2(255 BYTE),
  KOTA              VARCHAR2(50 BYTE),
  NEGARA            VARCHAR2(50 BYTE),
  KODE_POS          VARCHAR2(50 BYTE),
  KUALIFIKASI       VARCHAR2(1024 BYTE),
  HUBUNGAN          VARCHAR2(255 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_INFO_LAIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_INFO_LAIN_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_JASA
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  KODE_JASA         VARCHAR2(50 BYTE),
  NAMA_JASA         VARCHAR2(255 BYTE),
  TIPE              VARCHAR2(50 BYTE),
  TERDAFTAR         CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_JASA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_JASA, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_JASA_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_KINERJA
(
  KODE_VENDOR_HIST      INTEGER,
  KODE_VENDOR           INTEGER,
  TANGGAL               DATE,
  KODE_TENDER           VARCHAR2(10 BYTE),
  TIPE_KOMODITI         CHAR(1 BYTE),
  KODE_KEL_JASA_BARANG  VARCHAR2(20 BYTE),
  KODE_PARAM            VARCHAR2(50 BYTE),
  NAMA_PARAM            VARCHAR2(255 BYTE),
  PILIHAN_PARAM         INTEGER,
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_KINERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_TENDER, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_KINERJA_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_LAP_KEUANGAN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  MATA_UANG         VARCHAR2(3 BYTE),
  TAHUN             INTEGER,
  TIPE              VARCHAR2(50 BYTE),
  NILAI_ASSET       NUMBER(19,4),
  HUTANG            NUMBER(19,4),
  PENDAPATAN        NUMBER(19,4),
  LABA_BERSIH       NUMBER(19,4),
  KELAS             CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VND_HIST_L_KEU_PK
  PRIMARY KEY
  (KODE_VENDOR, MATA_UANG, TAHUN, TIPE, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VND_HIST_L_KEU_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_PENGALAMAN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  NAMA              VARCHAR2(255 BYTE),
  NAMA_PROYEK       VARCHAR2(255 BYTE),
  MATA_UANG         VARCHAR2(3 BYTE),
  NILAI             NUMBER(19,4),
  TGL_MULAI         DATE,
  TGL_BERAKHIR      DATE,
  KONTAK            VARCHAR2(255 BYTE),
  NO_KONTAK         VARCHAR2(50 BYTE),
  NO_KONTRAK        VARCHAR2(50 BYTE),
  KETERANGAN        VARCHAR2(4000 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_PENGALAMAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA, NAMA_PROYEK, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_PENGALAMAN_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_PERALATAN
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  KATEGORI          VARCHAR2(50 BYTE),
  NAMA_PERALATAN    VARCHAR2(255 BYTE),
  SPESIFIKASI       VARCHAR2(512 BYTE),
  TAHUN_PEMBUATAN   INTEGER,
  JUMLAH            NUMBER(18),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_PERALATAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_PERALATAN, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_PERALATAN_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_SERTIFIKAT
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  NAMA              VARCHAR2(255 BYTE),
  PENERBIT          VARCHAR2(255 BYTE),
  TIPE              VARCHAR2(50 BYTE),
  TIPE_LAIN         VARCHAR2(50 BYTE),
  BERLAKU_DARI      DATE,
  BERLAKU_HINGGA    DATE,
  NO_SERTIFIKAT     VARCHAR2(50 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_SERTIFIKAT_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_SERTIFIKAT_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_TENAGA_KERJA
(
  KODE_VENDOR_HIST     INTEGER,
  KODE_VENDOR          INTEGER,
  NAMA                 VARCHAR2(255 BYTE),
  TIPE                 VARCHAR2(50 BYTE),
  PENDIDIKAN_TERAKHIR  VARCHAR2(50 BYTE),
  KEAHLIAN             VARCHAR2(1024 BYTE),
  TAHUN_BERAKHIR       INTEGER,
  STATUS_PEGAWAI       VARCHAR2(50 BYTE),
  TIPE_PEGAWAI         VARCHAR2(50 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_TENAGA_KERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_TENAGA_KERJA_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_TIPE
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_VENDOR       INTEGER,
  TIPE_VENDOR       VARCHAR2(255 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_TIPE_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_VENDOR, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_TIPE_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_HIST_WILAYAH
(
  KODE_VENDOR_HIST  INTEGER,
  KODE_WILAYAH      INTEGER,
  KODE_VENDOR       INTEGER,
  KODE2_WILAYAH     INTEGER,
  WILAYAH           VARCHAR2(255 BYTE),
  NO_SMK            VARCHAR2(50 BYTE),
  TGL_SMK           DATE,
  BERLAKU_SMK       DATE,
  STATUS_AKTIF      CHAR(1 BYTE),
  TGL_REKAM         DATE,
  PETUGAS_REKAM     VARCHAR2(10 BYTE),
  TGL_UBAH          DATE,
  PETUGAS_UBAH      VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_HIST_WILAYAH_PK
  PRIMARY KEY
  (KODE_WILAYAH, KODE_VENDOR, KODE_VENDOR_HIST)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_HIST_WILAYAH_FK 
  FOREIGN KEY (KODE_VENDOR, KODE_VENDOR_HIST) 
  REFERENCES EP_VENDOR_HIST (KODE_VENDOR,KODE_VENDOR_HIST)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_IJIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  PENERBIT       VARCHAR2(250 BYTE),
  NO             VARCHAR2(50 BYTE),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_IJIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_IJIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_INFORMASI_LAIN
(
  KODE_VENDOR    INTEGER,
  TIPE           VARCHAR2(100 BYTE),
  NAMA           VARCHAR2(255 BYTE),
  ALAMAT         VARCHAR2(255 BYTE),
  KOTA           VARCHAR2(50 BYTE),
  NEGARA         VARCHAR2(50 BYTE),
  KODE_POS       VARCHAR2(50 BYTE),
  KUALIFIKASI    VARCHAR2(1024 BYTE),
  HUBUNGAN       VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_INFORMASI_LAIN_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_INFORMASI_LAIN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_JASA
(
  KODE_VENDOR    INTEGER,
  KODE_JASA      VARCHAR2(50 BYTE),
  NAMA_JASA      VARCHAR2(255 BYTE),
  TIPE           VARCHAR2(50 BYTE),
  TERDAFTAR      CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_JASA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_JASA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_JASA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_KANTOR
(
  KODE_VENDOR    INTEGER,
  KODE_KANTOR    VARCHAR2(5 BYTE),
  STATUS         CHAR(1 BYTE),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_KANTOR_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_KANTOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_KANTOR_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_KANTOR_FK2 
  FOREIGN KEY (KODE_KANTOR) 
  REFERENCES MS_KANTOR (KODE_KANTOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_KINERJA
(
  KODE_VENDOR           INTEGER,
  TANGGAL               DATE,
  KODE_TENDER           VARCHAR2(10 BYTE),
  TIPE_KOMODITI         CHAR(1 BYTE),
  KODE_KEL_JASA_BARANG  VARCHAR2(20 BYTE),
  KODE_PARAM            VARCHAR2(50 BYTE),
  NAMA_PARAM            VARCHAR2(255 BYTE),
  PILIHAN_PARAM         INTEGER,
  TGL_REKAM             DATE,
  PETUGAS_REKAM         VARCHAR2(10 BYTE),
  TGL_UBAH              DATE,
  PETUGAS_UBAH          VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_KINERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, KODE_TENDER)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_KINERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_KOMENTAR
(
  KODE_KOMENTAR  INTEGER,
  KODE_VENDOR    INTEGER,
  NAMA_KOMENTAR  VARCHAR2(50 BYTE),
  STATUS         VARCHAR2(10 BYTE),
  NAMA_VENDOR    VARCHAR2(500 BYTE),
  TGL_BUAT       DATE,
  TGL_SELESAI    DATE,
  URL            VARCHAR2(200 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_KOMENTAR_PK
  PRIMARY KEY
  (KODE_KOMENTAR, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_KOMENTAR_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_LAPORAN_KEUANGAN
(
  KODE_VENDOR    INTEGER,
  MATA_UANG      VARCHAR2(3 BYTE),
  TAHUN          INTEGER,
  TIPE           VARCHAR2(50 BYTE),
  NILAI_ASSET    NUMBER(19,4),
  HUTANG         NUMBER(19,4),
  PENDAPATAN     NUMBER(19,4),
  LABA_BERSIH    NUMBER(19,4),
  KELAS          CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_LAPORAN_KEUANGAN_PK
  PRIMARY KEY
  (KODE_VENDOR, MATA_UANG, TAHUN, TIPE)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_LAPORAN_KEUANGAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_NEGOISASI_HIS
(
  KODE_NEGOISASI  INTEGER,
  KODE_VENDOR     INTEGER,
  TIPE_KOMODITI   VARCHAR2(50 BYTE),
  PROD_EXP_ID     VARCHAR2(50 BYTE),
  TANGGAL         DATE,
  KETERANGAN      VARCHAR2(1024 BYTE),
  STATUS          VARCHAR2(50 BYTE),
  USERNAME        VARCHAR2(100 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_NEGOISASI_HIS_PK
  PRIMARY KEY
  (KODE_NEGOISASI)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_NEGOISASI_HIS_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_PENGALAMAN
(
  KODE_VENDOR    INTEGER,
  NAMA           VARCHAR2(255 BYTE),
  NAMA_PROYEK    VARCHAR2(255 BYTE),
  MATA_UANG      VARCHAR2(3 BYTE),
  NILAI          NUMBER(19,4),
  TGL_MULAI      DATE,
  TGL_BERAKHIR   DATE,
  KONTAK         VARCHAR2(255 BYTE),
  NO_KONTAK      VARCHAR2(50 BYTE),
  NO_KONTRAK     VARCHAR2(50 BYTE),
  KETERANGAN     VARCHAR2(4000 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VND_PENGALAMAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA, NAMA_PROYEK)
  ENABLE VALIDATE,
  CONSTRAINT EP_VND_PENGALAMAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_PERALATAN
(
  KODE_VENDOR      INTEGER,
  KATEGORI         VARCHAR2(50 BYTE),
  NAMA_PERALATAN   VARCHAR2(255 BYTE),
  SPESIFIKASI      VARCHAR2(512 BYTE),
  TAHUN_PEMBUATAN  INTEGER,
  JUMLAH           NUMBER(18),
  TGL_REKAM        DATE,
  PETUGAS_REKAM    VARCHAR2(10 BYTE),
  TGL_UBAH         DATE,
  PETUGAS_UBAH     VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_PERALATAN_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA_PERALATAN)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_PERALATAN_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_SERTIFIKAT
(
  KODE_VENDOR     INTEGER,
  NAMA            VARCHAR2(255 BYTE),
  PENERBIT        VARCHAR2(255 BYTE),
  TIPE            VARCHAR2(50 BYTE),
  TIPE_LAIN       VARCHAR2(50 BYTE),
  BERLAKU_DARI    DATE,
  BERLAKU_HINGGA  DATE,
  NO_SERTIFIKAT   VARCHAR2(50 BYTE),
  TGL_REKAM       DATE,
  PETUGAS_REKAM   VARCHAR2(10 BYTE),
  TGL_UBAH        DATE,
  PETUGAS_UBAH    VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_SERTIFIKAT_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_SERTIFIKAT_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TENAGA_KERJA
(
  KODE_VENDOR          INTEGER,
  NAMA                 VARCHAR2(255 BYTE),
  TIPE                 VARCHAR2(50 BYTE),
  PENDIDIKAN_TERAKHIR  VARCHAR2(50 BYTE),
  KEAHLIAN             VARCHAR2(1024 BYTE),
  TAHUN_BERAKHIR       INTEGER,
  STATUS_PEGAWAI       VARCHAR2(50 BYTE),
  TIPE_PEGAWAI         VARCHAR2(50 BYTE),
  TGL_REKAM            DATE,
  PETUGAS_REKAM        VARCHAR2(10 BYTE),
  TGL_UBAH             DATE,
  PETUGAS_UBAH         VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TENAGA_KERJA_PK
  PRIMARY KEY
  (KODE_VENDOR, NAMA)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TENAGA_KERJA_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_TIPE
(
  KODE_VENDOR    INTEGER,
  TIPE_VENDOR    VARCHAR2(255 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_TIPE_PK
  PRIMARY KEY
  (KODE_VENDOR, TIPE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_TIPE_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);


CREATE TABLE EP_VENDOR_WILAYAH
(
  KODE_WILAYAH   INTEGER,
  KODE_VENDOR    INTEGER,
  KODE2_WILAYAH  INTEGER,
  WILAYAH        VARCHAR2(255 BYTE),
  NO_SMK         VARCHAR2(50 BYTE),
  TGL_SMK        DATE,
  BERLAKU_SMK    DATE,
  STATUS_AKTIF   CHAR(1 BYTE),
  TGL_REKAM      DATE,
  PETUGAS_REKAM  VARCHAR2(10 BYTE),
  TGL_UBAH       DATE,
  PETUGAS_UBAH   VARCHAR2(10 BYTE),
  CONSTRAINT EP_VENDOR_WILAYAH_PK
  PRIMARY KEY
  (KODE_WILAYAH, KODE_VENDOR)
  ENABLE VALIDATE,
  CONSTRAINT EP_VENDOR_WILAYAH_FK 
  FOREIGN KEY (KODE_VENDOR) 
  REFERENCES EP_VENDOR (KODE_VENDOR)
  ENABLE VALIDATE
);
